export type Status = 'draft' | 'published' | 'archived';
export type AssignmentTarget = {
  builds: string[];
  brands: string[];
  locations: string[];
  schedule?: { startsAt: string; endsAt: string };
  trafficSplit?: number;
};
export type ButtonStateStyles = { fill: string; textColor: string; border: string; shadow: string };
export type CTAStyle = {
  text: string;
  fontFamily: string;
  size: number;
  weight: number;
  shape: 'pill' | 'rounded' | 'square';
  width: number;
  height: number;
  x: number;
  y: number;
  fill: string;
  gradient: string;
  border: string;
  textColor: string;
  states: { default: ButtonStateStyles; pressed: ButtonStateStyles; disabled: ButtonStateStyles; loading: ButtonStateStyles };
};
export type LayoutConfig = {
  backgroundRef: string;
  assetType: 'PNG' | 'JPG' | 'GIF' | 'MP4';
  scaling: 'cover' | 'contain' | 'custom';
  zoom: number;
  x: number;
  y: number;
  overlayOpacity: number;
  blur: number;
  gradient: 'none' | 'dark' | 'light' | 'brand';
  headline: string;
  subtext: string;
  fontFamily: string;
  headlineSize: number;
  bodySize: number;
  textShadow: boolean;
  glow: boolean;
  priceLabel: string;
  closeButton: boolean;
  bottomPlayButton: boolean;
  cta: CTAStyle;
  bottomCta: CTAStyle;
  confirmationCta: CTAStyle;
};
export type PaywallVersion = { version: number; createdAt: string; note: string; layout: LayoutConfig; status: Status };
export type PaywallTemplate = {
  id: string;
  name: string;
  status: Status;
  currentVersion: number;
  createdAt: string;
  updatedAt: string;
  assignments: AssignmentTarget;
  metrics: { conversionRate: number; engagement: number; revenuePerSession: number };
  layout: LayoutConfig;
  confirmation: LayoutConfig & { confetti: boolean; transition: 'fade' | 'slide' | 'zoom' | 'arcade'; autoCloseSeconds: number; secondaryCancel: boolean };
  versions: PaywallVersion[];
};
export type FlowConfig = {
  id: string;
  name: string;
  status: Status;
  lockedDefault?: boolean;
  currentVersion: number;
  screenOrder: string[];
  visibility: Record<string, boolean>;
  triggers: string[];
  entryFullScreenPaywall: boolean;
  ctaDestination: 'purchase' | 'confirmation' | 'home' | 'custom-route';
  confirmation: { enabled: boolean; placements: string[] };
  home: { categories: boolean; arrows: boolean; featuredRows: boolean; layout: 'grid' | 'carousel' };
  bottomCtaBehavior: 'immediate purchase' | 'confirmation screen' | 'full paywall' | 'custom route';
  tileClickBehavior: 'confirmation screen' | 'game info page' | 'game-specific paywall';
  gameInfo: { enabled: boolean; description: boolean; trailer: boolean; screenshots: boolean };
  perGamePaywalls: Record<string, string>;
  assignments: AssignmentTarget;
};
export type PricingRule = {
  id: string;
  name: string;
  active: boolean;
  priority: number;
  priceCents: number;
  currency: string;
  daysOfWeek: number[];
  startMinute: number;
  endMinute: number;
  assignments: { builds: string[]; brands: string[]; locations: string[] };
  promoOverride?: { active: boolean; label: string; priceCents: number; startsAt: string; endsAt: string };
  algorithmic: { demandWeight: number; usageWeight: number; conversionRateWeight: number };
  posMode: 'direct price update' | 'credit/discount line item';
  activates?: { flowId?: string; paywallId?: string };
  allowFreeOrNegative?: boolean;
};
export type Game = { id: string; title: string; category: string; description: string; trailer: string; screenshots: string[]; art: string };
export type PurchaseLock = { id: string; priceCents: number; currency: string; lockedAt: string; ruleId: string; expiresAt: string };
export type Context = { build: string; brand: string; location: string; now: Date };
